In [1]:
my_list = [1,2,3]
import numpy as np
arr = np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n--------------------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
--------------------
 [1 2 3]


In [2]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int64


In [3]:
print("A series of numbers:",np.arange(5,16)) # A series of numbers from low to high 

A series of numbers: [ 5  6  7  8  9 10 11 12 13 14 15]


In [4]:
print("Numbers spaced apart by 2:",np.arange(0,11,2)) # Numbers spaced apart by 2

Numbers spaced apart by 2: [ 0  2  4  6  8 10]


In [5]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [6]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [7]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print(np.linspace(1,5,21)) # insert numbers between the numbers like 21 numbers will be inserted between 1 to 5

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


# Zeroes, Ones, empty, and Identity **matriX**

> Indented block



In [8]:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]
Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
print("Vector of ones\n---------------------")
print(np.ones(5))
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]
Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [14]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [11]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary

Random number generation (from Uniform distribution)
[[0.33301989 0.29727338 0.56286336]
 [0.19704505 0.85524712 0.5530624 ]]


In [15]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.38153343 -1.01689443  1.10020259]
 [ 2.60601284 -0.11732368  0.01267572]
 [ 0.00837785 -1.56507741  0.33699688]
 [-0.7310812  -2.06401695  0.84651601]]


In [16]:
print("Random integer vector:",np.random.randint(1,100,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

Random integer vector: [ 3 51 58 69  3  7 63 18 62 79]

Random integer matrix
[[15 47 67 81]
 [87 70  1 32]
 [54 11 13 99]
 [71 82 81 63]]

20 samples drawn from a dice throw: [2 3 3 3 4 3 1 5 6 4 5 1 6 6 1 3 1 2 5 6]


# Reshaping, min, max, **sort**

In [17]:
from numpy.random import randint as ri
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)

A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A, kind='mergesort'))

M = ri(1,100,25).reshape(5,5) # Matrix of random interegrs
print("\n5x5 Matrix of random integers\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M, kind='mergesort')) # Default axis =1
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=0, kind='mergesort'))

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)

a looks like
 -------------------- 
 [27 41 73 33 65 92 54 44 34 33 10 53 95 81 59 96 80  5  1 45 21  9 50 75
 64 65 27 33 14 25] 
 --------------------

b looks like
 -------------------- 
 [[[27 41 73 33 65]
  [92 54 44 34 33]
  [10 53 95 81 59]]

 [[96 80  5  1 45]
  [21  9 50 75 64]
  [65 27 33 14 25]]] 
 --------------------

c looks like
 -------------------- 
 [[27 41 73 33 65]
 [92 54 44 34 33]
 [10 53 95 81 59]
 [96 80  5  1 45]
 [21  9 50 75 64]
 [65 27 33 14 25]] 
 --------------------

Vector of random integers
 -------------------------------------------------- 
 [90 15 37  6 47 79 83 10 87  3]

Here is the sorted vector
 -------------------------------------------------- 
 [ 3  6 10 15 37 47 79 83 87 90]

5x5 Matrix of random integers
 -------------------------------------------------- 
 [[98 75 72 66 75]
 [79  7 41 40 59]
 [93 80 77 75 50]
 [49 23 42 68 68]
 [37 35 43 25 40]]

Here is the sorted matrix along eac

In [18]:
print("Max of a:", a.max())
print("Max of b:", b.max())
print("Max of a location:", a.argmax())
print("Max of b location:", b.argmax())
print("Max of c location:", b.argmax())

Max of a: 96
Max of b: 96
Max of a location: 15
Max of b location: 15
Max of c location: 15


In [19]:
arr = np.arange(0,11)
print("Array:",arr)
print("Element at 7th index is:", arr[7])
print("Elements from 3rd to 5th index are:", arr[3:6])
print("Elements up to 4th index are:", arr[:4])
print("Elements from last backwards are:", arr[-1::-1])
print("3 Elements from last backwards are:", arr[-1:-6:-2])

arr = np.arange(0,21,2)
print("New array:",arr)
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Array: [ 0  1  2  3  4  5  6  7  8  9 10]
Element at 7th index is: 7
Elements from 3rd to 5th index are: [3 4 5]
Elements up to 4th index are: [0 1 2 3]
Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]
3 Elements from last backwards are: [10  8  6]
New array: [ 0  2  4  6  8 10 12 14 16 18 20]
Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [20]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)

print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][2])

print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,2])
print("\nRow or column extract\n----------------------")

print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix of random 2-digit numbers
--------------------------------
 [[24 96 23 99 78]
 [51 42 82 48 11]
 [96 97 60 14 74]]

Double bracket indexing
------------------------
Element in row index 1 and column index 2: 82

Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 82

Row or column extract
----------------------
Entire row at index 2: [96 97 60 14 74]
Entire column at index 3: [99 48 14]

Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[48 11]
 [14 74]]
Matrix with row indices 0 and 1 and column indices 1 and 3
 [[96 99]
 [42 48]]


In [21]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)

print("\nAddition\n------------------\n", mat1+mat2)
print("\nMultiplication\n------------------\n", mat1*mat2)
print("\nDivision\n------------------\n", mat1/mat2)
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)

print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)

print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,0.5))


1st Matrix of random single-digit numbers
----------------------------------------
 [[1 3 9]
 [2 5 6]
 [3 1 5]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[4 6 1]
 [6 3 8]
 [4 3 4]]

Addition
------------------
 [[ 5  9 10]
 [ 8  8 14]
 [ 7  4  9]]

Multiplication
------------------
 [[ 4 18  9]
 [12 15 48]
 [12  3 20]]

Division
------------------
 [[0.25       0.5        9.        ]
 [0.33333333 1.66666667 0.75      ]
 [0.75       0.33333333 1.25      ]]

Lineaer combination: 3*A - 2*B
-----------------------------
 [[-5 -3 25]
 [-6  9  2]
 [ 1 -3  7]]

Addition of a scalar (100)
-------------------------
 [[101 103 109]
 [102 105 106]
 [103 101 105]]

Exponentiation, matrix cubed here
----------------------------------------
 [[  1  27 729]
 [  8 125 216]
 [ 27   1 125]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[1.         1.73205081 3.        ]
 [1.41421356 2.23606798 2.44948974]
 [1.732050

**Broadcasting (super cool feature)**
NumPy operations are usually done on pairs of arrays on an element-by-element basis. In the simplest case, the two arrays must have exactly the same shape.

NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing dimensions, and works its way forward. Two dimensions are compatible when

they are equal, or
one of them is 1
If these conditions are not met, a ValueError: frames are not aligned exception is thrown, indicating that the arrays have incompatible shapes. The size of the resulting array is the maximum size along each dimension of the input arrays.

For more detail, please look up: https://docs.scipy.org/doc/numpy-1.10.1/user/basics.broadcasting.html

In [22]:
start = np.zeros((4,3)) # only takes 0 values 
print(start)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [23]:
# create a rank 1 ndarray with 3 values
add_rows = np.array([1, 0, 2])
print(add_rows)

[1 0 2]


In [24]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]
 [1. 0. 2.]]


In [25]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [26]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[0. 0. 0.]
 [1. 1. 1.]
 [2. 2. 2.]
 [3. 3. 3.]]


In [27]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+add_scalar)

[[100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]
 [100. 100. 100.]]


# Linear Algebra Operations
# Dot/Inner/Outer products

In [28]:
A = np.arange(1,10).reshape(3,3)
B = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of 1-9 single-digit numbers (A)\n","-"*50,"\n",A)
print("\n2nd Matrix of random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nDot product of A and B (for 2D arrays it is equivalent to matrix multiplication) \n","-"*80,"\n",np.dot(A,B))

A = np.arange(1,6)
B = ri(1,10,5)
print("\n1st Vector of 1-5 numbers (A)\n","-"*50,"\n",A)
print("\n2nd Vector of 5 random single-digit numbers (B)\n","-"*50,"\n",B)

print("\nInner product of vectors A and B \n","-"*50,"\n",np.inner(A,B), "(sum of all pairwise elements)")
print("\nOuter product of vectors A and B \n","-"*50,"\n",np.outer(A,B))


1st Matrix of 1-9 single-digit numbers (A)
 -------------------------------------------------- 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

2nd Matrix of random single-digit numbers (B)
 -------------------------------------------------- 
 [[6 6 6]
 [7 9 1]
 [7 3 8]]

Dot product of A and B (for 2D arrays it is equivalent to matrix multiplication) 
 -------------------------------------------------------------------------------- 
 [[ 41  33  32]
 [101  87  77]
 [161 141 122]]

1st Vector of 1-5 numbers (A)
 -------------------------------------------------- 
 [1 2 3 4 5]

2nd Vector of 5 random single-digit numbers (B)
 -------------------------------------------------- 
 [1 5 7 3 6]

Inner product of vectors A and B 
 -------------------------------------------------- 
 74 (sum of all pairwise elements)

Outer product of vectors A and B 
 -------------------------------------------------- 
 [[ 1  5  7  3  6]
 [ 2 10 14  6 12]
 [ 3 15 21  9 18]
 [ 4 20 28 12 24]
 [ 5 25 35 15 30]]


# TRANSPOSE

In [29]:
A = ri(1,10,9).reshape(3,3)
print("\n3x3 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix transpose\n","-"*50,"\n",np.transpose(A))

B = ri(1,10,6).reshape(3,2)
print("\n3x2 Matrix of random single-digit numbers\n","-"*50,"\n",B)
print("\n2x3 Matrix transpose\n","-"*50,"\n",np.transpose(B))
print("\nMatrix multiplication of B and B-transpose\n","-"*50,"\n",np.dot(B, np.transpose(B)))


3x3 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[5 9 4]
 [3 3 9]
 [3 1 5]]

Matrix transpose
 -------------------------------------------------- 
 [[5 3 3]
 [9 3 1]
 [4 9 5]]

3x2 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[2 5]
 [7 1]
 [6 4]]

2x3 Matrix transpose
 -------------------------------------------------- 
 [[2 7 6]
 [5 1 4]]

Matrix multiplication of B and B-transpose
 -------------------------------------------------- 
 [[29 19 32]
 [19 50 46]
 [32 46 52]]


In [30]:
A = ri(1,10,16).reshape(4,4)
print("\n4x4 Matrix of random single-digit numbers\n","-"*50,"\n",A)
print("\nMatrix trace\n","-"*50,"\n",np.trace(A))
print("\nMatrix trace with ofset +1 (upper triangle)\n","-"*50,"\n",np.trace(A,offset=1))
print("\nMatrix trace with ofset -1 (lower triangle)\n","-"*50,"\n",np.trace(A,offset=-1))


4x4 Matrix of random single-digit numbers
 -------------------------------------------------- 
 [[3 4 4 2]
 [3 7 8 3]
 [4 4 8 1]
 [3 6 8 2]]

Matrix trace
 -------------------------------------------------- 
 20

Matrix trace with ofset +1 (upper triangle)
 -------------------------------------------------- 
 13

Matrix trace with ofset -1 (lower triangle)
 -------------------------------------------------- 
 15


# **Eigenvalues and eigenvectors**

In [31]:
A = np.random.randn(9).reshape(3,3)
print("Original matrix\n",A)
print("\n")
w,v=np.linalg.eig(A)
print("Eigenvalues:\n",w)
print("\n")
print("Eigenvectors:\n",v)

Original matrix
 [[-0.58484836 -0.16513042 -0.60510658]
 [-1.72620268 -1.20274089  0.2035209 ]
 [ 1.30142373 -0.08847346 -1.91543571]]


Eigenvalues:
 [-0.86145472+0.j         -1.42078512+0.42588327j -1.42078512-0.42588327j]


Eigenvectors:
 [[ 0.22121315+0.j          0.06812626-0.25032527j  0.06812626+0.25032527j]
 [-0.91042055+0.j          0.82645345+0.j          0.82645345-0.j        ]
 [ 0.34956997+0.j         -0.30760317-0.39376523j -0.30760317+0.39376523j]]


# Linear equation solving, matrix inverse, linear least suqare
You can directly solve linear system of equations using NumPy writing only one line of code.

Suppose you want to solve the following set of equations for (x,y,z). It is easy to see that (2,1,5) are the unique solutions.

2x + 5y + z = 14;

3x - 2y - z = -1;

x - 3y + z = 4

In [32]:
A = np.array([[2,5,1],[3,-2,-1],[1,-3,1]])
B = np.array([14,-1,4])
x = np.linalg.solve(A,B)

print("The solutions are:",x)

The solutions are: [2. 1. 5.]
